test pinggy integration

diff --git a/.github/workflows/workflow.yml b/.github/workflows/workflow.yml
--- a/.github/workflows/workflow.yml
+++ b/.github/workflows/workflow.yml
@@ -110,10 +110,25 @@ jobs: # Conjunto de las tareas
       id: pinggy
       run: |
         nohup pinggy http 9000 --urlfile pinggy.url > pinggy.log 2>&1 &
-        sleep 10  # espera a que arranque pinggy
+        
+        # Esperar hasta que aparezca el archivo (máx. 30s)
+        for i in {1..30}; do
+          if [ -f pinggy.url ]; then
+            break
+          fi
+          sleep 1
+        done
+        
+        if [ ! -f pinggy.url ]; then
+          echo "❌ Error: pinggy.url no se creó"
+          cat pinggy.log  # Mostrar log para diagnosticar
+          exit 1
+        fi
+        
         url=$(cat pinggy.url)
         echo "Pinggy URL: $url"
         echo "url=$url" >> $GITHUB_OUTPUT
+
 
     - name: 📊SONARQUBE - Instalando Sonar Scanner...
       run: |
